version: '3.8'

services:
  f1-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - f1-data:/app
    environment:
      - PORT=8002
    restart: unless-stopped

volumes:
  f1-data: